insert into fact(rarity, fact_content) values('rare', 'В молодости черноморские окуни в основном самки, но уже к пяти годам они радикально меняют пол');
insert into fact(rarity, fact_content) values('common', 'С ноября тысяча девятьсот сорок первого года в Советском Союзе был налог на бездетность. Он составлял шесть процентов от всей зарплаты.');
insert into fact(rarity, fact_content) values('common', 'В среднем одинокие мужчины на два с половиной сантиметра ниже ростом, чем женатые.');
insert into fact(rarity, fact_content) values('common', 'Ежедневная двадцатиминутная прогулка сжигает около трех килограмм жира в год.');
insert into fact(rarity, fact_content) values('common', 'Автором электрического стула был простой дантист.');
insert into fact(rarity, fact_content) values('common', 'Длина всех кровеносных сосудов человеческого тела — около девяносто шести тысяч километров.');
insert into fact(rarity, fact_content) values('common', 'Ушная сера необходима для здоровья ушей.');
insert into fact(rarity, fact_content) values('common', 'За всю историю регистрации температуры в России самой холодной зимой была зима тысяча семьсот сорокового года.');
insert into fact(rarity, fact_content) values('common', 'Три самые богатые семьи в мире имеют больше активов, чем сорок восемь беднейших стран.');
insert into fact(rarity, fact_content) values( 'common', 'Человек — единственное животное, которое плачет из-за эмоций.');
insert into fact(rarity, fact_content) values( 'common', 'Во время полета в самолете скорость роста волос у человека удваивается.');
insert into fact(rarity, fact_content) values( 'common', ' Одиннадцать процентов людей на земле левши.');
insert into fact(rarity, fact_content) values( 'common', 'Люди теряют около шестиста тысяч частиц кожи каждый час.');
insert into fact(rarity, fact_content) values( 'uncommon', 'В городе Крескилл в Нью-Джерси все коты и кошки должны носить три колокольчика, чтобы птицы всегда знали об их расположении.');
insert into fact(rarity, fact_content) values( 'uncommon', 'За среднестатистическую жизнь сердце делает три миллиарда триста миллионов ударов.');
insert into fact(rarity, fact_content) values( 'uncommon', 'Тонкая кишка человека имеет длину порядка двух с половиной метров.');
insert into fact(rarity, fact_content) values( 'uncommon', 'Юлий Цезарь носил лавровый венок, чтобы скрыть начинающуюся лысину.');
insert into fact(rarity, fact_content) values( 'uncommon', 'Человеческий волос толще мыльной пленки примерно в пять тысяч раз.');
insert into fact(rarity, fact_content) values( 'uncommon', 'Луна легче Земли в восемьдесят раз.');
insert into fact(rarity, fact_content) values( 'uncommon', 'Вольфганг Моцарт, один раз прослушав в Ватикане многоголосое духовное сочинение Аллегри, за ночь записал точную копию произведения.');
insert into fact(rarity, fact_content) values( 'uncommon', 'В городе Тегази в Сахаре встречаются дома со стенами из каменной соли. Это одно из самых сухих мест на Земле.');
insert into fact(rarity, fact_content) values( 'uncommon', 'В Англии наезд на собаку наказывается строже, чем наезд на человека.');
insert into fact(rarity, fact_content) values( 'uncommon', 'До 18-ого века у России не было флага.');
insert into fact(rarity, fact_content) values( 'rare', 'Древние египтяне использовали тени для глаз, чтобы уберечься от конъюнктивита и трахомы.');
insert into fact(rarity, fact_content) values( 'rare', 'После того как Александр Македонский завез из одного своего индийского похода в Грецию тростниковый сахар, его сразу же начали называть “индийской солью”.');
insert into fact(rarity, fact_content) values( 'rare', 'У блондинов больше волос.');
insert into fact(rarity, fact_content) values( 'rare', 'Египетские пирамиды были такими же древними для жителей Древнего Рима, как для нас сегодня сама Римская Империя.');
insert into fact(rarity, fact_content) values( 'legendary', 'Кость в пять раз прочнее стали.');
insert into fact(rarity, fact_content) values( 'legendary', 'У жирафа и человека одинаковое количество шейных позвонков.');
insert into fact(rarity, fact_content) values( 'celestial', 'Почти тридцать процентов женщин, узнав, что выиграли в лотерею, прячут выигрышный билет в лифчик.');